### ISSUE TITLE
Wal2 json example

### ISSUE THREAD

**Issue by andreievg** [openmsupply/remote-server#212]
https://www.dropbox.com/s/m91w0ie5a5qh308/wal2json.mov?dl=0

in this branch: https://github.com/openmsupply/remote-server/compare/wal2json-example

```SQL
SELECT * FROM pg_create_logical_replication_slot('sync_slot', 'wal2json')
```

```SQL
CREATE TABLE wal_check(
 id varchar serial primary key,
 var1 varchr,
 var2 varchar
)
```

```SQL
SELECT * FROM pg_logical_slot_peek_changes('sync_slot', NULL, NULL, 'format-version', '1','add-tables', 'public.wal_check', 'include-pk', 'true','add-msg-prefixes',  'wal2json')
```

```SQL
INSERT INTO wal_check (var1, var2) VALUES ('1', 'one')
```
```SQL
INSERT INTO wal_check (var1, var2) VALUES ('2', 'two')
```

```SQL
SELECT * FROM pg_logical_slot_peek_changes('sync_slot', NULL, NULL, 'format-version', '1','add-tables', 'public.wal_check', 'include-pk', 'true','add-msg-prefixes',  'wal2json')
```

```SQL
SELECT * FROM pg_replication_slot_advance('sync_slot', '0/16618A0'::pg_lsn);
```

```SQL
INSERT INTO wal_check (var1, var2) VALUES ('3', 'three');
INSERT INTO wal_check (var1, var2) VALUES ('5', 'four');
```

```SQL
Begin;
INSERT INTO wal_check (var1, var2) VALUES ('3', 'three');
INSERT INTO wal_check (var1, var2) VALUES ('5', 'four');
Commit;
```

```SQL
SELECT * FROM pg_logical_slot_peek_changes('sync_slot', NULL, NULL, 'format-version', '1','add-tables', 'public.wal_check', 'include-pk', 'true','add-msg-prefixes',  'wal2json')
```

```SQL
update wal_check set var2 = 'три' where var1 = '3';
update wal_check set var1 = '4' where var2 = 'four';
```

```SQL
SELECT * FROM pg_logical_slot_peek_changes('sync_slot', NULL, NULL, 'format-version', '1','add-tables', 'public.wal_check', 'include-pk', 'true','add-msg-prefixes',  'wal2json')
```

I was hoping that update events would only included columns that were changed, but that's not the case. Only columns that exceed total page size limit (via TOAST) will be excluded if unchanged, refer to: https://debezium.io/blog/2019/10/08/handling-unchanged-postgres-toast-values/

![Atomic Sync Basic](https://user-images.githubusercontent.com/26194949/125366872-20050c00-e3cb-11eb-9fd3-c035211c103a.png)
![Atomic Sync Postgres ](https://user-images.githubusercontent.com/26194949/125366878-22fffc80-e3cb-11eb-8b4b-0944136100cd.png)

https://app.diagrams.net/#G1EkSEVYJQl0GRf6itIpGEZUYyZSawlShr
https://app.diagrams.net/#G1U1KbI-h1puDPBfjj9J1tyUgbOYqqnUCH

**Comment by Chris-Petty** [comment]
If I followed correctly, that's pretty cool!

Some Qs:

- Translation layers? Say if remote is on schema1, and server is on schema2, what'd happen? If translation is the answer where do we put it
  - Wait did I see right that this method also picks up the changes to schema? If the data is strictly for db replication purposes, then that's pretty sweet if centrally each site had its own DB (Adrian has mentioned using an FDW to abstract a bit, dunno if it'd place nice if sites had slightly different schemas for what ever reason). For such a thing as transfers, merges and any other RPC, a messaging system would cover that easily (sync already basically is a handcrafted message queue system).
 - Might tie into the above, but I assume this only works from remote sites -> central server? Current there isn't a site ID indicating the other direction (might be in `syncQ`)?

**Comment by adrianwb** [comment]
I've been playing a bit with this as well, with a docker compose setup with 4 instances of PG running in Ubuntu WSL2, plus one more container for pgadmin! As I understand it (so far - still learning!), logical replication is a lot more flexible than physical replication as it operates at the high-level SQL rather than low-level binary, but it still expects the destination schema to be consistent with the sending one, so I suspect that we'll still need to handle that somehow (I haven't tried it yet with mismatched schemas to see what happens!).

What I've managed so far is to have a central PG instance which publishes its "central" data (just items and stores so far) and then each of my remote stores subscribe to that (each with their own replication slot). Going the other way, I'm trying to setup each remote site to publish its "store" data (just stock so far) and have the central site subscribe to each of those. The problem is that in real-life we can't assume that the necessary ports on remote sites will be accessible => might be able to do log shipping (not sure if that works for logical replication, but that's another thing that I've yet to try!).

If not, that's where wal2json (or a similar logical decoder - see https://wiki.postgresql.org/wiki/Logical_Decoding_Plugins) comes in - it will let us basically convert the WAL into a readable format to send back to the central server => that's the equivalent of our incoming sync records, but all auto-generated from the WAL at the remote site end (which we could pre-process to look more like our current sync records?).  The central server still has to parse that into equivalent SQL statements - I haven't been able to find anything which does this already, apart from some talk about _logical2sql_ e.g. https://www.highgo.ca/2019/08/22/an-overview-of-logical-replication-in-postgresql/, but it doesn't seem to actually exist yet :-(

Interesting you can send messages via wal2json as well (see examples at https://github.com/eulerto/wal2json), so we might be able to use that for the complicated stuff like transfers. Another interesting thing I found is that you can configure logical replication to include the previous values as well as the updated ones (e.g. https://debezium.io/documentation/reference/postgres-plugins.html) => we could use that with wal2json to preprocess the JSON so that it only actually sends the changed fields.

**Comment by andreievg** [comment]
@adrianwb, thanks for the summary, I came across much of the same info you've described (wal logic replication seems cool)

I was hoping for now we would just use wal as our remote sync queue (still do translation to our current format of sync records to send to central), and central would have to do integration of all records in a http request in a transaction (maintain data integrity). As for decoding, wal2json seems more digestible then standard decoding (If we dont' use wal2josn, I think we would be implementing much of the same logic as wal2json to consume wal logs)

> Interesting you can send messages via wal2json as well

It's cool ay ! I wonder if we want to have a table for messages still (maybe for record keeping, and for remote sites when say a message arriving on remote wants to change a field of a record but records would be locked ? (although I am not sure if we going to lock records at this stage).

I think `REPLICA IDENTITY FULL` is too much overhead on every write ? Craig mentioned maybe we can use it for some tables. The least overhead way I could think of, to get change by field, is to have a clone DB, compares wal updates against actual values, then logs the fields that actually changed, then updates the clone. This seems like too many moving pieces though. 

If we use trigger to get by field changes, we can still store transaction it belongs too, but to figure out what fields have changed we need to compare OLD to NEW, which i think is too much overhead.

From my understanding, in systems with loads of data, in relational DB, it's the writes that's hard to scale, thus I am thinking about overhead on that front

> What I've managed so far is to have a central PG instance which publishes its "central" data

Great I think this research would be very useful when we re-write central server. (v2, form what I understand)

>. The problem is that in real-life we can't assume that the necessary ports on remote sites will be accessible => might be able to do log shipping (not sure if that works for logical replication, but that's another thing that I've yet to try!).
> The central server still has to parse that into equivalent SQL statements 

Definitely think that our remote push modal (rather then central pull), is the way to go. IMO converting from json to SQL statement for a particular records is a few lines of code, should be reasonably trivial. The hardest part would be the keeping schema in sync (or api versioning, or sync update binaries to remotes, etc..)

**Comment by andreievg** [comment]
@Chris-Petty 

> Translation layers? Say if remote is on schema1, and server is on schema2, what'd happen? If translation is the answer where do we put it
> Wait did I see right that this approach also picks up the changes to schema? If the data is strictly for db replication purposes, then that's pretty sweet if centrally each site had its own DB (Adrian has mentioned using an FDW to abstract a bit, dunno if it'd play nice if sites had slightly different schemas for what ever reason). For such a thing as transfers, merges and any other RPC, a messaging system would cover that easily (sync already basically is a handcrafted message queue system).

I was only really looking at figuring out how we can do transactional sync queue. As for dynamic schema alignment, I think it's easier to just sync the new version to the remote, and make sure versions always match for syns.

> Might tie into the above, but I assume this only works from remote sites -> central server? Current there isn't a site ID indicating the other direction (might be in syncQ)?

If we end up doing something similar on central (when we move away form 4D), we can insert extra bits of arbitrary data to the wal log of the transaction. (maybe that would help identify site id ?)

> If it is only from remote -> central, what's the difference between this and using standard pg replication?

We are syncing with 4D, and I think what Adrian pointing out that subscriptions seems to listen on port (remote probably will have dynamic ip)

**Comment by adrianwb** [comment]
I've now got a proof-of-concept with store-sharding and logical replication up and running with WSL2/Ubuntu/Docker on my Windows10 laptop (32Gb RAM really helps :-)) and a couple of "remote" machines - a Beelink mini PC (Windows 10) and an elderly Macbook Pro (High Sierra) both running Postgres and PGadmin:

Laptop setup (Windows side):

 - create firewall rule to open SSH port
 - install WSL2 and Ubuntu 20.04 
 - install docker desktop (with WSL2 integration)
 - pull docker images for "postgres" and "dpage/pgadmin"
 - lookup WSL2 internal IP address (different each time WSL2 is started): `wsl hostname -I` e.g. 172.27.180.42
 - forward SSH traffic to WSL2 (different each time WSL2 is started): `netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=22 connectaddress=172.27.180.42 connectport=22`

Laptop setup (Ubuntu side):

 - run SSH server (with certificates setup for "adrian" to allow passwordless access): `sudo service ssh start`
 - Postgres upgraded to v13 (from v12, for compatibility with postgres docker image)
 - Use `netstat -tulpn` to see which ports are active

Docker setup:

One pgadmin instance and four postgres instances (my laptop internal IP is 192.168.2.10 a.k.a. "central.server"):

- primary on port 5500 (central-data)
- central on port 5432
- remote-one on port 5501 (store-one)
- remote-two on port 5502 (store-two)

Here's my `docker-compose.yml`:

```
version: '3'

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "central.server:192.168.2.10"
    environment:
      - PGADMIN_DEFAULT_EMAIL=msupply@sussol.net
      - PGADMIN_DEFAULT_PASSWORD=secret
    volumes:
      - ./storage:/var/lib/pgadmin/storage

  primary:
    image: postgres
    container_name: postgres-primary
    ports:
      - "5500:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "central.server:192.168.2.10"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./conf/primary/postgresql.conf:/etc/postgresql.conf
      - ./conf/primary:/home/conf
      - ./scripts/primary/create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh
      - ./scripts/primary:/home/scripts
      - ./sql:/home/sql
    command: postgres -c config_file=/etc/postgresql.conf

  central:
    image: postgres
    container_name: postgres-central
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "central.server:192.168.2.10"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./conf/central/postgresql.conf:/etc/postgresql.conf
      - ./conf/central:/home/conf
      - ./scripts/central/create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh
      - ./scripts/central:/home/scripts
      - ./sql:/home/sql
    command: postgres -c config_file=/etc/postgresql.conf

  remote-one:
    image: postgres
    container_name: postgres-remote-one
    ports:
      - "5501:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "central.server:192.168.2.10"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./conf/remote-one/postgresql.conf:/etc/postgresql.conf
      - ./conf/remote-one:/home/conf
      - ./scripts/remote-one/create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh
      - ./scripts/remote-one:/home/scripts
      - ./sql:/home/sql
    command: postgres -c config_file=/etc/postgresql.conf

  remote-two:
    image: postgres
    container_name: postgres-remote-two
    ports:
      - "5502:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "central.server:192.168.2.10"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./conf/remote-two/postgresql.conf:/etc/postgresql.conf
      - ./conf/remote-two:/home/conf
      - ./scripts/remote-two/create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh
      - ./scripts/remote-two:/home/scripts
      - ./sql:/home/sql
    command: postgres -c config_file=/etc/postgresql.conf
```

- postgresql.conf has been edited from the default to set `wal_level = logical`
- `host.docker.internal` is the internal IP address of the Ubuntu host - needed when setting up the servers in pgadmin
- `scripts` and `sql` (should really be called `common` or `shared` instead!) are folders containing psql/bash scripts shared with the docker container
  - current versions: [work.tar.gz](https://github.com/openmsupply/remote-server/files/7001300/work.tar.gz)
  - many of them have been parameterised to take e.g. the store code
  - `create_tables.sh` automatically initialises the DB the first time the container is run 
  - after all instances have been initialised, CLI into each container in turn (primary first, then central and then remote-one & two) and run further scripts to setup replication from the primary and populate with some test data: `bash` and then `/home/scripts/initialise_tables.sh`
  - when all of those are complete, then CLI into the central container and run another script to setup replication from the remote stores: `bash` and then `/home/scripts/update_store_tables.sh`
- syncing of central data from the primary, and syncing of regular store data from the remote sites is taken care of at DB level with logical replication => all we need to worry about are the exceptions e.g. transfers, messages etc. (and it _might_ be possible to handle those as well - need to think some more about that...)
- if the DB structure is updated, that will pause replication until the subscribing site has also been updated => if you update the central server first, central data won't sync out to the remote sites until they've been updated, but remote sites will still be able to sync their store data in
 
Postgres:

- `central_data`: editable on primary, replicated to central and from there replicated to remote-one/two
  - `central.item` central table for items (UUID, name, code)
  - `central.store` central table for stores (UUID, name, code, port): store code is used in many scripts as a tag, store port corresponds to the Postgres port allocated for that store's instance
- `central_data`: editable on primary, replicated to central and from there replicated to remote-one/two
  - `central.item` central table for items (UUID, name, code)
- `stores`
  - `central.item` foreign central table for items
  - `central.item` foreign central table for stores
  - `store.stock` store table for stock (UUID, item ID, store ID, batch, expiry, quantity, price): partitioned by store ID
    - `store.stock_CODE` local stock table for each store with matching store code which exists on the postgres server - foreign table to its own separate `store_CODE` database, editable on the instance corresponding to its port, and replicated to central 
    - `store.stock_other` as default partition for anything belonging to a store not present on the postgres server

Reverse SSH tunnel (still in progress):

Each remote site will run postgres on its own port (corresponding to the store), which is reverse tunnelled to the central server, and with the central postgres server port-forwarded e.g. `ssh -R 5505:localhost:5505 -L 5432:localhost:5432 adrian@192.168.2.10` with appropriate certificates setup to allow password-less authentication, and kitty (fork of putty) on Windows and autossh on Mac/Linux to maintain the connection:
- on the central server, you can see (with `netstat -tulpn`) which connections are up at any given time :-)
- on the central server, you can see the remote data in real time :-))
- on the remote site, you can see the central data in real time :-)))

Creating new stores/instances (still in progress):

- create a new store on the primary with unique code and port
- wait for it to sync
- on the instance CLI corresponding to the store's port, run `/home/scripts/create_new_store.sh CODE`
- on central instance CLI, run `/home/scripts/create_new_store.sh CODE` and then run `/home/scripts/create_new_slot.sh CODE`

Moving stores between instances - TODO

- should just be a matter of exporting the data and re-importing, but might need to change foreign table/replication settings?
