### ISSUE TITLE
error on windows (exit code: 3)

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/remote-server#560]
When running on windows, the process usually crashes with the error `process didn't exit successfully` and `(exit code: 3)`
However, usually retrying will work with no other changes e.g.
![Screen Shot 2021-11-02 at 4 21 10 PM](https://user-images.githubusercontent.com/9192912/140671319-dc137870-3e15-458a-acc7-a414c57542de.png)

I've re-intialised the database on the demo server in order to test the sync changes and after retrying 18 times, the server still does not start.

**Comment by mark-prins** [comment]
update: I had configured the env var `DATABASE_URL` in order to work around the issue with quotes in params when  migrating and to make migration easier. Turns out, that having the env var configured causes the server to crash. have removed and the server is running

**Comment by clemens-msupply** [comment]
what was your config and the value of DATABASE_URL?

**Comment by mark-prins** [comment]
The environment variable was set using this: `set DATABASE_URL=postgres://postgres:-redacted-password-@localhost:5432/omsupply`

( this is on windows, so the env var uses `set` rather than `export` )

and the `base.yaml` is this:

```
server:
  port: 8008
sync:
  url: http://localhost:8080
  username: "kawakawa"
  password: "pass"
  interval: 300
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "-redacted-password-"
  database_name: "omsupply"
auth:
  token_secret: "token-secret"
```

the env var worked fine for the migration 😄  and means that I don't have to type in as much when running migration.. nor do I have to remember about the single quotes being a problem! but it must be causing an issue with Diesel when actually running the server.
